spring:
  application:
    name: posts
  data:
    mongodb:
      uri: mongodb://admin:afaboi@localhost:37017/posts?authSource=admin&authMechanism=SCRAM-SHA-256
      authentication-database: admin  #Authentication database
      auto-index-creation: true   # Automatically create indexes
server:
  port: 8101

posts:
  jwt:
     secret: ajkyM2QzMjhkYzM4ZjAyODk0MzQzODlkZjg0OTAwNGtLOUQ5MzBESzIzRDAzRGhmZTkyODRqZjQ4ampkU0RGaGRmMzkzcjN3ZXdnajkyM2QzMjhkYzM4ZjAyODk0MzQzODlkZjg0OTAwNGtLOUQ5MzBESzIzRDAzRGhmZTkyODRqZjQ4ampkU0RGaGRmMzkzcjN3ZXdnajkyM2QzMjhkYzM4ZjAyODk0MzQzODlkZjg0OTAwNGtLOUQ5MzBESzIzRDAzRGhmZTkyODRqZjQ4ampkU0RGaGRmMzkzcjN3ZXdn
  test:
     prova: sièunaprova
